app:
  name: Go-Web # 应用程序的名称
  port: :8080 # docker容器的端口

database: # 数据库的配置
  dsn: root:123456@tcp(my-mysql:3306)/test?charset=utf8mb4&parseTime=True&loc=Local  # 这里地址为my-mysql:3306
  MaxIdleConns: 11 # 最初的空闲数是11
  MaxOpenConns: 114 # 最大的打开的链接数是114
  ConnMaxLifetimeHours: 1 # 持续时间

redis:
  enabled: true
  addr: my-redis:6379
  password: ""
  db: 0

superadmin: # 超级管理员账号
  username: superadmin
  password: admin123456

# 这里的天气密钥采用的是腾讯的api,由腾讯旗下的天气服务提供-这里无需密钥因此无需配置，可见https://wis.qq.com/weather/common接口

local_api:
  baseURL: "https://restapi.amap.com/v3/ip" # 高德地图的默认api
  apiKey: "0270ba7fa32241c95ff5446901b99f6b"
  LocationDailyLimit: 100 # 单个用户的使用上限制，硬编码默认为100

translation_api:
  provider: "Kimi K2" # 可以是 "openai", "azure", "google" 等
  apiKey: "sk-jyhcMDgKVf92eTIGK50HHYtivSBEi3JtUAjHOLgs4QgYHDhx"
  baseURL: "https://api.moonshot.cn/v1" # OpenAI API的基础URL
  model: "moonshot-v1-8k" # 这里使用kimi的模型
  LocationDailyLimit: 100 # 单个用户的使用上限制，硬编码默认为100

upload:
  totalSize: 500
  fileSize: 50
  storagepath: "files"
